---
- name: create groups
  ansible.builtin.group:
    name: "{{ item.key }}"
    system: "{{ item.value.system | default('no') }}"
    gid: "{{ item.value.gid | default(omit) }}"
    state: present
  loop: "{{ account_groups | dict2items }}"
