---
- name: copy skeleton templates files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/etc/skel/{{ item.dest | default(item.src | basename | regex_replace('\\.j2', '') ) }}"
    mode: 'u=rw,go=r'
  when: item.os_family | default(ansible_os_family)|lower == ansible_os_family | lower
  loop: "{{ skel_templates }}"
